import http from 'k6/http';
import { check } from 'k6';
import { SharedArray } from 'k6/data';

// Load the 5000 test tokens from JSON file generated by generate_tokens.py
const tokens = new SharedArray('test tokens', function () {
  return JSON.parse(open('./test_tokens.json'));
});

// Configure the load test
export const options = {
  scenarios: {
    // Scenario to simulate 1000s of users hitting the refresh endpoint in the same second
    refresh_storm: {
      executor: 'ramping-arrival-rate',
      startRate: 100, // Start with 100 requests per second
      timeUnit: '1s',
      preAllocatedVUs: 1500, // Pre-allocate VUs to handle the burst
      maxVUs: 4000,          // Maximum allowed VUs
      stages: [
        { target: 1000, duration: '10s' }, // Ramp up to 1000 rps
        { target: 2000, duration: '20s' }, // Ramp up to 2000 rps (the "storm")
        { target: 0, duration: '10s' },    // Scale down
      ],
    },
  },
  thresholds: {
    // 95% of requests must complete below 1000ms
    http_req_duration: ['p(95)<1000'],
    // Less than 1% of requests are allowed to fail
    http_req_failed: ['rate<0.01'],
  },
};

export default function () {
  // Get a token pair unique to this iteration, or random if more iterations than tokens
  // Using modulo to wrap around if there are more iterations than tokens
  const tokenPair = tokens[__VU % tokens.length];

  const baseUrl = __ENV.BASE_URL || 'http://localhost:8000';
  const url = `${baseUrl}/auth/refresh`;
  
  const payload = null; // No body for this POST request

  const params = {
    headers: {
      'Authorization': `Bearer ${tokenPair.access_token}`,
    },
    cookies: {
      'refresh_token': tokenPair.refresh_token,
    },
  };

  const res = http.post(url, payload, params);

  // We expect a 200 OK and a new access token in the JSON response
  check(res, {
    'status is 200': (r) => r.status === 200,
    'has new access token': (r) => {
        try {
            return r.json('access_token') !== undefined;
        } catch(e) {
            return false;
        }
    }
  });
}
