sonar.projectKey=g2-smartadopt
sonar.projectName=smartadopt

# Rutas de código fuente
sonar.sources=frontend/src,backend/app

# Rutas de pruebas
sonar.tests=frontend/src,backend/tests

# Exclusiones (sacan los tests y dependencias de la carpeta sources)
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/__pycache__/**,**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx,**/*.stories.tsx

# Inclusiones de Tests (asegura que la carpeta tests SOLO analice archivos de pruebas reales)
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx,**/*.stories.tsx,backend/tests/**/*

# Reportes de cobertura
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml
