sonar.projectKey=g2-smartadopt
sonar.projectName=smartadopt

# Rutas de código fuente
sonar.sources=frontend/src,backend/app

# Rutas de pruebas
sonar.tests=frontend/src,backend/tests

# Exclusiones
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/__pycache__/**,**/*.spec.ts,**/*.test.ts,**/*.stories.tsx

# Reportes de cobertura
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml
